let gameSeq = []; //Stores the sequence of button generated by the game
let userSeq = []; //Stores the sequence of button entered by the user
let highScore = 0; //High score tracking variable
let btns = ['yellow', "red", "purple", "green"]; //Array storing all the buttons
let h4 = document.querySelector("h4"); //Heading for displaying the high score

let started = false; //Defines if the game has started or not
let level = 0; //Level tracking variable 
let h2 = document.querySelector('h2'); //Heading for displaying the level

//Function for starting the game and increasing level
document.addEventListener("keypress", function() {
    if (started == false) { //Start the game if not already started
        console.log("Game is started");
        started = true;
    }
    let a = document.querySelector('a'); 
    a.classList.add("hide"); //Adds the 'hide' class in the class list of anchor tag to hide it after the start of the game
    levelUp();
});

//Function for making the button flash by game 
function gameFlash(btn) {
    btn.classList.add("flash"); //Flashes the button
    setTimeout(function() {
        btn.classList.remove("flash");
    }, 250); //Removes the 'flash' class after 250 milliseconds | Making the flash temporary
}

//Function for making the button flash by user clicking
function userFlash(btn) {
    btn.classList.add("userFlash"); //Flashing the button green if the user clicked the right sequence
    setTimeout(function() {
        btn.classList.remove("userFlash");
    }, 250); 
}

//Level up function which updates the score and also generates the next random button
function levelUp() {
    userSeq = [];
    level++;
    highScore = Math.max(highScore, level); //Tracking the all time high score of a single user at once
    h2.innerText = `Level ${level}`; //Displaying score

    //Choose random button
    let randomIdx = Math.floor(Math.random() * 3); //Generating random index between 0 to 3
    let randomColor = btns[randomIdx]; //Selecting random color on the basis of random number
    let randomBtn = document.querySelector(`.${randomColor}`);

    gameSeq.push(randomColor); //Adding in color sequence by game
    console.log(gameSeq);
    gameFlash(randomBtn); //flashing the next random button
}

// Function to check if the entered button is in the correct sequence or not
function checkBtn(idx) {
    if (userSeq[idx] == gameSeq[idx]) {
        if (userSeq.length == gameSeq.length) { //Updates the level at 1 sec interval
            setTimeout(levelUp, 1000);
        }
    }
    else {
        h2.innerHTML = `Game over! Your score was <b>${level} <br> Press any key to restart`
        document.querySelector("body").style.backgroundColor = "red"; //For showing the game over screen by turning BG color red
        setTimeout(() => {
            document.querySelector("body").style.backgroundColor = "white"; //Again setting the BG color to normal
        }, 150);
        
        h4.innerText = `High Score = ${highScore}`; //For displaying high score
        h4.classList.remove("hide");
        reset();
    }
}

function btnPress() {
    let btn = this;
    userFlash(btn);

    userColor = btn.getAttribute("id"); //Extracting the color of the button clicked by the user in the form of 'id'
    userSeq.push(userColor); //Adding the color of the button clicked by the user to the user sequence

    checkBtn(userSeq.length - 1);
}

let allBtns = document.querySelectorAll(".btn");
for(btn of allBtns) {
    btn.addEventListener("click", btnPress);
}

function reset() {
    started = false;
    gameSeq = [];
    userSeq = [];
    level = 0;
}